### PR TITLE
Allow jQuery 3.x

### PR DESCRIPTION
**Pull request by Locutus83**
But not 4.x

Per https://jubianchi.github.io/semver-check/#/%3E%3D1.7.1%20%3C4.0.0/3.3.1 this change should work.

### CODE REVIEW

**Review by HTMLGuyLLC — APPROVED** [review]

**Comment by HTMLGuyLLC** [comment]
Is there a reason to stop at 4.x? Is it incompatible?

**Comment by Locutus83** [comment]
We just don't know if it is and, since they promised a lot of breaking changes, I'm guessing it might be good to verify before it is listed as "OK".

**Comment by Locutus83** [comment]
I personally would be OK with or without the "<4.0.0" restriction, I just thought it would be good to "future-proof" it a bit...

**Comment by HTMLGuyLLC** [comment]
Agreed, Until it's tested this is a good move. I just don't want to forget to come back and test/allow 4.x.

**Pull request merged**
